name: 'Publish to PyPi'
description: 'A subcomponent of pulumi-package-publish'

inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  codeartifact_repository:
    description: 'AWS CodeArtifact Repository'
    required: true
  codeartifact_domain:
    description: 'AWS CodeArtifact Domain'
    required: true
  codeartifact_domain_owner:
    description: 'AWS CodeArtifact Domain Owner'
    required: true
  codeartifact_region:
    description: 'AWS CodeArtifact Region'
    required: true
  artifact_name:
    description: 'The name of the artifact to publish'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHONVERSION }}
    - name: Install Twine
      run: python -m pip install pip twine virtualenv
      shell: bash
    - name: Login to AWS CodeArtifact
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      run: aws codeartifact login
        --tool twine
        --repository ${{ inputs.codeartifact_repository }}
        --domain ${{ inputs.codeartifact_domain }}
        --domain-owner ${{ inputs.codeartifact_domain_owner }}
        --region ${{ inputs.codeartifact_region }}
      shell: bash
    - name: Download python SDK
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ github.workspace }}/sdk/
    - name: Uncompress python SDK
      run: tar -zxf ${{ github.workspace }}/sdk/python.tar.gz -C
        ${{ github.workspace }}/sdk/python
      shell: bash
    - name: Publish Python SDK
      run: echo "Publishing Pip package to CodeArtifact:" &&
        twine upload
        -r codeartifact
        "${{ github.workspace }}/sdk/python/bin/dist/*"
        --skip-existing
        --verbose
      shell: bash
